url: https://keithdhd.github.io
baseurl: 

# Site settings
title: Keith Douglas
email: keith@keithdouglas.co.uk
description: "Keith Douglas - Web Developer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Keith Douglas
  pic: 1
  position: Web Developer
  social:
    - title: twitter
      url: http://twitter.com/KDHDouglas
    - title: github
      url: http://github.com/keithdhd


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/KDHDouglas
  - title: github
    url: http://github.com/keithdhd


# Build settings
markdown: kramdown
permalink: pretty