# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Keith Douglas
tagline:          'Web Developer'
description:      'Keith Douglas, web developer'
url:              http://www.keithdouglas.co.uk

author:
  name:           'Keith Douglas'
  url:            https://twitter.com/KDHDouglas

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/keithdh/keithdhd.github.io
